global:
  scrape_interval: 15s
  evaluation_interval: 15s # How often to evaluate rules

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ["localhost:9093"] # Alertmanager default port

# Rule files for alerts
rule_files:
  - "alerts.yml"

scrape_configs:
  # Scrape the Celery exporter
  - job_name: "celery-exporter"
    static_configs:
      - targets: ["localhost:9808"]

  # Scrape FastAPI custom metrics
  - job_name: "fastapi"
    static_configs:
      - targets: ["localhost:8000"]
    metrics_path: "/metrics"

  # Scrape FastAPI Prometheus exporter endpoint
  - job_name: "fastapi-prometheus"
    static_configs:
      - targets: ["localhost:8000"]
    metrics_path: "/prometheus/metrics/exporter"
